### ISSUE TITLE
[Feature Request]: Hardware Fixes

### ISSUE THREAD

**Issue by LiinkPK** [SirMangler/pcsx2#16]
### Description

No "Hardware Fixes" tab in order to fix issues like ghosting.

### Reason

Missing in this version.

### Examples

Feature included in previous versions.

**Comment by TheRhysWyrill** [comment]
Hardware Fixes are a "Per-game" thing, you can find the option by going to `Game Properties > Graphics Settings`.

**Comment by LiinkPK** [comment]
My apologies, and thank you for the clarification. Not seeing it in general settings made me believe it was removed in current versions.
