### ISSUE TITLE
Scaling bug on Series S ?

### ISSUE THREAD

**Issue by mmmago** [SirMangler/pcsx2#19]
**Describe the bug**
App is not scaling correctly on my Series S.

**To Reproduce**
1. Just launch the app...

**Expected behavior**
App being scaled properly ?

**Screenshots**

![IMG_0407](https://github.com/SirMangler/pcsx2/assets/76073612/377a9a49-a80b-4b18-86a9-4c9da7296af7)

**Desktop (please complete the following information):**
 - Console: Series S
 - Version 10.0.22621.4912

**Does this occur on PC PCSX2?**
//

**Comment by GABO1423** [comment]
This is the fault of your TV. Change the Overscan/aspect ratio setting from 16:9 to whatever setting it has to show the fullscreen. Either way, not a XBSX2 issue.
