### ISSUE TITLE
[BUG]: XBSX2.0.3 wont start games

### ISSUE THREAD

**Issue by TLiley2** [SirMangler/pcsx2#28]
### Describe the Bug

Clicking "start" or the 'A' button on a game wont start the game

### Reproduction Steps

1. Click Start File
2. Select iso file
3. game wont start 

### Expected Behavior

1. Click Start File
2. Select iso file
3. game will start

### PCSX2 Revision

2.0.3

### Operating System

Xbox Series X

**Comment by harrysof** [comment]
Have you tried formatting your flash drive using [XboxmediaUsb](https://github.com/SvenGDK/XboxMediaUSB/releases) Tool ?
Try doing that and make sure to include the bios file

**Comment by TLiley2** [comment]
I figured it out. There is a bug in XBSX2.0.3 that can cause the bios folder to corrupt. So I had to delete the corrupted folder and replace it. and now it works
